import { z } from 'zod';
import {
  zColor,
  zFontSize,
  zHAlign,
  zLineStyle,
  zLineWidth,
  zOpacity,
  zVAlign,
  zFontFamily,
  DEFAULT_FONT_FAMILY,
} from '../../framework';

export const rectangleStyleSchema = z.object({
  borderColor: zColor,
  borderOpacity: zOpacity,
  borderWidth: zLineWidth,
  borderStyle: zLineStyle,
  fillEnabled: z.boolean(),
  fillColor: zColor,
  fillOpacity: zOpacity,
  extendLeft: z.boolean(),
  extendRight: z.boolean(),
  showMiddleLine: z.boolean(),
  middleLineColor: zColor,
  middleLineOpacity: zOpacity,
  middleLineWidth: zLineWidth,
  middleLineStyle: zLineStyle,
  showPriceRange: z.boolean(),
  showBarsRange: z.boolean(),
  text: z.string().max(2000),
  textColor: zColor,
  fontSize: zFontSize,
  fontFamily: zFontFamily,
  bold: z.boolean(),
  italic: z.boolean(),
  textHAlign: zHAlign,
  textVAlign: zVAlign,
  textWrap: z.boolean(),
});

export type RectangleStyle = z.infer<typeof rectangleStyleSchema>;

export const RECTANGLE_DEFAULTS: RectangleStyle = {
  borderColor: '#9c27b0',
  borderOpacity: 1,
  borderWidth: 1,
  borderStyle: 'solid',
  fillEnabled: true,
  fillColor: '#9c27b0',
  fillOpacity: 0.2,
  extendLeft: false,
  extendRight: false,
  showMiddleLine: false,
  middleLineColor: '#9c27b0',
  middleLineOpacity: 1,
  middleLineWidth: 1,
  middleLineStyle: 'dashed',
  showPriceRange: false,
  showBarsRange: false,
  text: '',
  textColor: '#9c27b0',
  fontSize: 14,
  fontFamily: DEFAULT_FONT_FAMILY,
  bold: false,
  italic: false,
  textHAlign: 'center',
  textVAlign: 'middle',
  textWrap: true,
};
