import { z } from 'zod';
import {
  zColor,
  zFontSize,
  zHAlign,
  zLineEnd,
  zLineStyle,
  zLineWidth,
  zOpacity,
  zVAlign,
  zFontFamily,
  DEFAULT_FONT_FAMILY,
} from '../../framework';

export const trendLineStyleSchema = z.object({
  color: zColor,
  opacity: zOpacity,
  lineWidth: zLineWidth,
  lineStyle: zLineStyle,
  extendLeft: z.boolean(),
  extendRight: z.boolean(),
  startEnd: zLineEnd,
  endEnd: zLineEnd,
  showMiddlePoint: z.boolean(),
  showPriceRange: z.boolean(),
  showPercentChange: z.boolean(),
  showBarsRange: z.boolean(),
  showDateRange: z.boolean(),
  showDistance: z.boolean(),
  showAngle: z.boolean(),
  alwaysShowStats: z.boolean(),
  statsPosition: zHAlign,
  text: z.string().max(2000),
  textColor: zColor,
  fontSize: zFontSize,
  fontFamily: zFontFamily,
  bold: z.boolean(),
  italic: z.boolean(),
  textAlign: zHAlign,
  textPosition: zVAlign,
});

export type TrendLineStyle = z.infer<typeof trendLineStyleSchema>;

export const TREND_LINE_DEFAULTS: TrendLineStyle = {
  color: '#2962ff',
  opacity: 1,
  lineWidth: 2,
  lineStyle: 'solid',
  extendLeft: false,
  extendRight: false,
  startEnd: 'none',
  endEnd: 'none',
  showMiddlePoint: false,
  showPriceRange: true,
  showPercentChange: true,
  showBarsRange: true,
  showDateRange: true,
  showDistance: false,
  showAngle: true,
  alwaysShowStats: false,
  statsPosition: 'right',
  text: '',
  textColor: '#2962ff',
  fontSize: 14,
  fontFamily: DEFAULT_FONT_FAMILY,
  bold: false,
  italic: false,
  textAlign: 'center',
  textPosition: 'top',
};
